In [1]:
import pandas as pd
import numpy as np
import umap

/home/milo/miniconda3/envs/cytometry/lib/python3.8/site-packages/umap/__init__.py:9: UserWarning: Tensorflow not installed; ParametricUMAP will be unavailable
  warn("Tensorflow not installed; ParametricUMAP will be unavailable")

In [2]:
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.graph_objects as go

In [3]:
results = pd.read_csv("object_results.csv")

In [4]:
results

      Object Id  XMin  XMax  YMin  ...  Membrane Area (µm²)  Nucleus Area (µm²)  Nucleus Perimeter (µm)  Nucleus Roundness
0             0  1404  1407   853  ...                   10                   0                       0           0.000000
1             1  1058  1062   913  ...                    8                   0                       0           0.000000
2             2  1058  1065   915  ...                   33                   0                       0           0.000000
3             3  1159  1161  1333  ...                    6                   0                       0           0.000000
4             4  1480  1503   790  ...                    0                 151                      57           0.599115
...         ...   ...   ...   ...  ...                  ...                 ...                     ...                ...
4371       4371   425   451   783  ...                    0                  61                      30           0.859234
4372       4372   767   795   787  ...                    0                  78                      36           0.811386
4373       4373   117   135   785  ...                    0                  45                      26           0.833814
4374       4374   508   532   785  ...                    0                 101                      38           0.841830
4375       4375   669   696   786  ...                    0                  43                      25           0.838024

[4376 rows x 36 columns]

In [64]:
ignore_columns = "Object Id,XMin,XMax,YMin,YMax,Cell Area (µm²),Cytoplasm Area (µm²),Membrane Area (µm²),Nucleus Area (µm²),Nucleus Perimeter (µm),Nucleus Roundness"

In [65]:
ignore_columns.split(",")

['Object Id', 'XMin', 'XMax', 'YMin', 'YMax', 'Cell Area (µm²)', 'Cytoplasm Area (µm²)', 'Membrane Area (µm²)', 'Nucleus Area (µm²)', 'Nucleus Perimeter (µm)', 'Nucleus Roundness']

In [69]:
results.loc[:,~results.columns.isin(ignore_columns.split(","))]

ValueError: Item wrong length 1 instead of 4376.

In [5]:
results.iloc[:,5:30]

      171Yb_Renin Cell Intensity  175Lu_Aqu1 Cell Intensity  ...  170Er_CD3 Cell Intensity  89Y_CD45 Cell Intensity
0                      16.600000                    0.00000  ...                  0.000000                      0.0
1                       0.000000                18021.87500  ...                  0.000000                      0.0
2                       5.627119                27317.44100  ...                  0.000000                      0.0
3                       0.000000                    0.00000  ...                  0.000000                      0.0
4                       1.870787                 1060.32300  ...                 10.233146                      0.0
...                          ...                        ...  ...                       ...                      ...
4371                    2.902098                13988.01400  ...                  0.000000                      0.0
4372                    2.903790                  261.80760  ...                  0.000000                      0.0
4373                    6.973282                15722.19800  ...                264.038180                      0.0
4374                    1.400844                   63.42405  ...                  0.000000                      0.0
4375                    1.778571                  218.98572  ...                  0.000000                      0.0

[4376 rows x 25 columns]

In [6]:
embedding = umap.UMAP().fit_transform(results.iloc[:,5:30])

In [7]:
embedding

array([[ 8.56306   , 12.188403  ],
       [-4.1615553 ,  5.5718403 ],
       [-4.09222   ,  5.4051    ],
       ...,
       [ 0.35631892,  6.4561944 ],
       [ 8.897394  ,  6.042398  ],
       [ 9.459021  ,  6.0291305 ]], dtype=float32)

In [25]:
embedding_df = pd.DataFrame(embedding).rename(columns={0: "umap_1", 1: "umap_2"})

In [18]:
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.express as px

In [27]:
results_with_umap = pd.concat([embedding_df.reset_index(drop=True), results], axis=1)

In [28]:
external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']
app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

Index(['Object Id', 'XMin', 'XMax', 'YMin', 'YMax',
       '171Yb_Renin Cell Intensity', '175Lu_Aqu1 Cell Intensity',
       '176Yb_H3 Cell Intensity', '191Ir_DNA1 Cell Intensity',
       '193Ir_DNA2 Cell Intensity', '141Pr_aSMA Cell Intensity',
       '143Nd_Vimentin Cell Intensity', '145Nd_Aqu2 Cell Intensity',
       '146Nd_Nestin Cell Intensity', '147Sm_B-Cat Cell Intensity',
       '148Nd_Calbindin Cell Intensity', '150Nd_CD86 Cell Intensity',
       '151Eu_CD31 Cell Intensity', '152Sm_CD66b Cell Intensity',
       '153Eu_Uromodulin Cell Intensity', '156Gd_CD4 Cell Intensity',
       '159Tb_CD68 Cell Intensity', '161Dy_CD20 Cell Intensity',
       '162Dy_CD8a Cell Intensity', '164Dy_Cytokeratin7 Cell Intensity',
       '165Ho_Megalin Cell Intensity', '166Er_Col-IV Cell Intensity',
       '169Tm_WT1 Cell Intensity', '170Er_CD3 Cell Intensity',
       '89Y_CD45 Cell Intensity', 'Cell Area (µm²)', 'Cytoplasm Area (µm²)',
       'Membrane Area (µm²)', 'Nucleus Area (µm²)', 'Nucleus Perimeter (µm)',
       'Nucleus Roundness'],
      dtype='object')

In [ ]:
app.layout = html.Div([
    html.Label('Color'),
    dcc.Dropdown(
        options=results.columns,
        value='171Yb_Renin Cell Intensity'
    ),
], style={'columnCount': 2})

if __name__ == '__main__':
    app.run_server(debug=True)

In [34]:
import sklearn

In [71]:
import sklearn.manifold

In [72]:
tsne_embeddings = sklearn.manifold.TSNE().fit_transform(results.iloc[:,5:30])

In [73]:
tsne_embeddings

array([[ 58.36256 ,  38.371086],
       [-85.45492 ,  28.185621],
       [-84.128746,  29.554667],
       ...,
       [-35.164665,  12.907146],
       [ 28.462345, -18.355503],
       [ 33.007477, -17.449331]], dtype=float32)